//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Repositories.CaliforniaLifelineDireactApplicationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", ConfigurationName="CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap")]
    public interface DirectApplicationWrapperServiceSoap {
        
        // CODEGEN: Generating message contract since message CheckCustomerStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/CheckCustomerStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse CheckCustomerStatus(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/CheckCustomerStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse> CheckCustomerStatusAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest request);
        
        // CODEGEN: Generating message contract since message DirectApplicationRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/DirectApplicationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse DirectApplicationRequest(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/DirectApplicationRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse> DirectApplicationRequestAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest request);
        
        // CODEGEN: Generating message contract since message CheckApplicationPrintStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/CheckApplicationPrintStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse CheckApplicationPrintStatus(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DirectApplicationWrapper.Web.Svc/CheckApplicationPrintStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse> CheckApplicationPrintStatusAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DirectApplicationService/")]
    public partial class DirectApplicationRequestSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ocnField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private string usernameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ocn {
            get {
                return this.ocnField;
            }
            set {
                this.ocnField = value;
                this.RaisePropertyChanged("Ocn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCustomerStatus", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class    CheckCustomerStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://DirectApplicationService/")]
        public LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string ocn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=1)]
        public string ultsTelephoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=2)]
        public string namePrefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=3)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=4)]
        public string initials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=5)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=6)]
        public string nameSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=7)]
        public string serviceAddress1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=8)]
        public string serviceAddress2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=9)]
        public string serviceAddressCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=10)]
        public string serviceAddressState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=11)]
        public string serviceAddressZip5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=12)]
        public string serviceAddressZip4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=13)]
        public string priorUltsTelephoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=14)]
        public string ttyQualifiedSecondLine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=15)]
        public string activityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=16)]
        public string SSN4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=17)]
        public string dateOfBirth;
        
        public CheckCustomerStatusRequest() {
        }
        
        public CheckCustomerStatusRequest(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string priorUltsTelephoneNumber, 
                    string ttyQualifiedSecondLine, 
                    string activityType, 
                    string SSN4, 
                    string dateOfBirth) {
            this.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            this.ocn = ocn;
            this.ultsTelephoneNumber = ultsTelephoneNumber;
            this.namePrefix = namePrefix;
            this.firstName = firstName;
            this.initials = initials;
            this.lastName = lastName;
            this.nameSuffix = nameSuffix;
            this.serviceAddress1 = serviceAddress1;
            this.serviceAddress2 = serviceAddress2;
            this.serviceAddressCity = serviceAddressCity;
            this.serviceAddressState = serviceAddressState;
            this.serviceAddressZip5 = serviceAddressZip5;
            this.serviceAddressZip4 = serviceAddressZip4;
            this.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            this.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            this.activityType = activityType;
            this.SSN4 = SSN4;
            this.dateOfBirth = dateOfBirth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCustomerStatusResponse", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class CheckCustomerStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string CheckCustomerStatusResult;
        
        public CheckCustomerStatusResponse() {
        }
        
        public CheckCustomerStatusResponse(string CheckCustomerStatusResult) {
            this.CheckCustomerStatusResult = CheckCustomerStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectApplicationRequest", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class DirectApplicationRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://DirectApplicationService/")]
        public LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string ocn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=1)]
        public string subscriberAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=2)]
        public string customerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=3)]
        public string ultsTelephoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=4)]
        public string namePrefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=5)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=6)]
        public string initials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=7)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=8)]
        public string nameSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=9)]
        public string serviceAddress1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=10)]
        public string serviceAddress2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=11)]
        public string serviceAddressCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=12)]
        public string serviceAddressState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=13)]
        public string serviceAddressZip5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=14)]
        public string serviceAddressZip4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=15)]
        public string billingFirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=16)]
        public string billingInitial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=17)]
        public string billingLastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=18)]
        public string billingAddress1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=19)]
        public string billingAddress2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=20)]
        public string billingAddress3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=21)]
        public string billingAddress4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=22)]
        public string billingAddress5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=23)]
        public string billingCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=24)]
        public string billingStateCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=25)]
        public string billingZip5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=26)]
        public string billingZip4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=27)]
        public string contactPhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=28)]
        public string languageCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=29)]
        public string brailleLargeFont;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=30)]
        public string ultsServiceStartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=31)]
        public string ultsRecertificationDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=32)]
        public string priorUltsTelephoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=33)]
        public string disconnectDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=34)]
        public string ttyQualifiedSecondLine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=35)]
        public string driversLicenseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=36)]
        public string activityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=37)]
        public string tribalLand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=38)]
        public string serviceType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=39)]
        public string rateGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=40)]
        public string modifiedEffectiveDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=41)]
        public string directApplication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=42)]
        public string SSN4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=43)]
        public string dateOfBirth;
        
        public DirectApplicationRequestRequest() {
        }
        
        public DirectApplicationRequestRequest(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string subscriberAccountNumber, 
                    string customerCode, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string billingFirstName, 
                    string billingInitial, 
                    string billingLastName, 
                    string billingAddress1, 
                    string billingAddress2, 
                    string billingAddress3, 
                    string billingAddress4, 
                    string billingAddress5, 
                    string billingCity, 
                    string billingStateCode, 
                    string billingZip5, 
                    string billingZip4, 
                    string contactPhoneNumber, 
                    string languageCode, 
                    string brailleLargeFont, 
                    string ultsServiceStartDate, 
                    string ultsRecertificationDate, 
                    string priorUltsTelephoneNumber, 
                    string disconnectDate, 
                    string ttyQualifiedSecondLine, 
                    string driversLicenseNumber, 
                    string activityType, 
                    string tribalLand, 
                    string serviceType, 
                    string rateGroup, 
                    string modifiedEffectiveDate, 
                    string directApplication, 
                    string SSN4, 
                    string dateOfBirth) {
            this.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            this.ocn = ocn;
            this.subscriberAccountNumber = subscriberAccountNumber;
            this.customerCode = customerCode;
            this.ultsTelephoneNumber = ultsTelephoneNumber;
            this.namePrefix = namePrefix;
            this.firstName = firstName;
            this.initials = initials;
            this.lastName = lastName;
            this.nameSuffix = nameSuffix;
            this.serviceAddress1 = serviceAddress1;
            this.serviceAddress2 = serviceAddress2;
            this.serviceAddressCity = serviceAddressCity;
            this.serviceAddressState = serviceAddressState;
            this.serviceAddressZip5 = serviceAddressZip5;
            this.serviceAddressZip4 = serviceAddressZip4;
            this.billingFirstName = billingFirstName;
            this.billingInitial = billingInitial;
            this.billingLastName = billingLastName;
            this.billingAddress1 = billingAddress1;
            this.billingAddress2 = billingAddress2;
            this.billingAddress3 = billingAddress3;
            this.billingAddress4 = billingAddress4;
            this.billingAddress5 = billingAddress5;
            this.billingCity = billingCity;
            this.billingStateCode = billingStateCode;
            this.billingZip5 = billingZip5;
            this.billingZip4 = billingZip4;
            this.contactPhoneNumber = contactPhoneNumber;
            this.languageCode = languageCode;
            this.brailleLargeFont = brailleLargeFont;
            this.ultsServiceStartDate = ultsServiceStartDate;
            this.ultsRecertificationDate = ultsRecertificationDate;
            this.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            this.disconnectDate = disconnectDate;
            this.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            this.driversLicenseNumber = driversLicenseNumber;
            this.activityType = activityType;
            this.tribalLand = tribalLand;
            this.serviceType = serviceType;
            this.rateGroup = rateGroup;
            this.modifiedEffectiveDate = modifiedEffectiveDate;
            this.directApplication = directApplication;
            this.SSN4 = SSN4;
            this.dateOfBirth = dateOfBirth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectApplicationRequestResponse", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class DirectApplicationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string DirectApplicationRequestResult;
        
        public DirectApplicationRequestResponse() {
        }
        
        public DirectApplicationRequestResponse(string DirectApplicationRequestResult) {
            this.DirectApplicationRequestResult = DirectApplicationRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckApplicationPrintStatus", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class CheckApplicationPrintStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://DirectApplicationService/")]
        public LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=1)]
        public string transactionId;
        
        public CheckApplicationPrintStatusRequest() {
        }
        
        public CheckApplicationPrintStatusRequest(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, string documentId, string transactionId) {
            this.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            this.documentId = documentId;
            this.transactionId = transactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckApplicationPrintStatusResponse", WrapperNamespace="http://DirectApplicationWrapper.Web.Svc/", IsWrapped=true)]
    public partial class CheckApplicationPrintStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DirectApplicationWrapper.Web.Svc/", Order=0)]
        public string CheckApplicationPrintStatusResult;
        
        public CheckApplicationPrintStatusResponse() {
        }
        
        public CheckApplicationPrintStatusResponse(string CheckApplicationPrintStatusResult) {
            this.CheckApplicationPrintStatusResult = CheckApplicationPrintStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DirectApplicationWrapperServiceSoapChannel : LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DirectApplicationWrapperServiceSoapClient : System.ServiceModel.ClientBase<LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap>, LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap {
        
        public DirectApplicationWrapperServiceSoapClient() {
        }
        
        public DirectApplicationWrapperServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DirectApplicationWrapperServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectApplicationWrapperServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectApplicationWrapperServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.CheckCustomerStatus(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest request) {
            return base.Channel.CheckCustomerStatus(request);
        }
        
        public string CheckCustomerStatus(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string priorUltsTelephoneNumber, 
                    string ttyQualifiedSecondLine, 
                    string activityType, 
                    string SSN4, 
                    string dateOfBirth) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.ocn = ocn;
            inValue.ultsTelephoneNumber = ultsTelephoneNumber;
            inValue.namePrefix = namePrefix;
            inValue.firstName = firstName;
            inValue.initials = initials;
            inValue.lastName = lastName;
            inValue.nameSuffix = nameSuffix;
            inValue.serviceAddress1 = serviceAddress1;
            inValue.serviceAddress2 = serviceAddress2;
            inValue.serviceAddressCity = serviceAddressCity;
            inValue.serviceAddressState = serviceAddressState;
            inValue.serviceAddressZip5 = serviceAddressZip5;
            inValue.serviceAddressZip4 = serviceAddressZip4;
            inValue.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            inValue.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            inValue.activityType = activityType;
            inValue.SSN4 = SSN4;
            inValue.dateOfBirth = dateOfBirth;
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse retVal = ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).CheckCustomerStatus(inValue);
            return retVal.CheckCustomerStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse> LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.CheckCustomerStatusAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest request) {
            return base.Channel.CheckCustomerStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusResponse> CheckCustomerStatusAsync(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string priorUltsTelephoneNumber, 
                    string ttyQualifiedSecondLine, 
                    string activityType, 
                    string SSN4, 
                    string dateOfBirth) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckCustomerStatusRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.ocn = ocn;
            inValue.ultsTelephoneNumber = ultsTelephoneNumber;
            inValue.namePrefix = namePrefix;
            inValue.firstName = firstName;
            inValue.initials = initials;
            inValue.lastName = lastName;
            inValue.nameSuffix = nameSuffix;
            inValue.serviceAddress1 = serviceAddress1;
            inValue.serviceAddress2 = serviceAddress2;
            inValue.serviceAddressCity = serviceAddressCity;
            inValue.serviceAddressState = serviceAddressState;
            inValue.serviceAddressZip5 = serviceAddressZip5;
            inValue.serviceAddressZip4 = serviceAddressZip4;
            inValue.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            inValue.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            inValue.activityType = activityType;
            inValue.SSN4 = SSN4;
            inValue.dateOfBirth = dateOfBirth;
            return ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).CheckCustomerStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.DirectApplicationRequest(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest request) {
            return base.Channel.DirectApplicationRequest(request);
        }
        
        public string DirectApplicationRequest(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string subscriberAccountNumber, 
                    string customerCode, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string billingFirstName, 
                    string billingInitial, 
                    string billingLastName, 
                    string billingAddress1, 
                    string billingAddress2, 
                    string billingAddress3, 
                    string billingAddress4, 
                    string billingAddress5, 
                    string billingCity, 
                    string billingStateCode, 
                    string billingZip5, 
                    string billingZip4, 
                    string contactPhoneNumber, 
                    string languageCode, 
                    string brailleLargeFont, 
                    string ultsServiceStartDate, 
                    string ultsRecertificationDate, 
                    string priorUltsTelephoneNumber, 
                    string disconnectDate, 
                    string ttyQualifiedSecondLine, 
                    string driversLicenseNumber, 
                    string activityType, 
                    string tribalLand, 
                    string serviceType, 
                    string rateGroup, 
                    string modifiedEffectiveDate, 
                    string directApplication, 
                    string SSN4, 
                    string dateOfBirth) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.ocn = ocn;
            inValue.subscriberAccountNumber = subscriberAccountNumber;
            inValue.customerCode = customerCode;
            inValue.ultsTelephoneNumber = ultsTelephoneNumber;
            inValue.namePrefix = namePrefix;
            inValue.firstName = firstName;
            inValue.initials = initials;
            inValue.lastName = lastName;
            inValue.nameSuffix = nameSuffix;
            inValue.serviceAddress1 = serviceAddress1;
            inValue.serviceAddress2 = serviceAddress2;
            inValue.serviceAddressCity = serviceAddressCity;
            inValue.serviceAddressState = serviceAddressState;
            inValue.serviceAddressZip5 = serviceAddressZip5;
            inValue.serviceAddressZip4 = serviceAddressZip4;
            inValue.billingFirstName = billingFirstName;
            inValue.billingInitial = billingInitial;
            inValue.billingLastName = billingLastName;
            inValue.billingAddress1 = billingAddress1;
            inValue.billingAddress2 = billingAddress2;
            inValue.billingAddress3 = billingAddress3;
            inValue.billingAddress4 = billingAddress4;
            inValue.billingAddress5 = billingAddress5;
            inValue.billingCity = billingCity;
            inValue.billingStateCode = billingStateCode;
            inValue.billingZip5 = billingZip5;
            inValue.billingZip4 = billingZip4;
            inValue.contactPhoneNumber = contactPhoneNumber;
            inValue.languageCode = languageCode;
            inValue.brailleLargeFont = brailleLargeFont;
            inValue.ultsServiceStartDate = ultsServiceStartDate;
            inValue.ultsRecertificationDate = ultsRecertificationDate;
            inValue.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            inValue.disconnectDate = disconnectDate;
            inValue.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            inValue.driversLicenseNumber = driversLicenseNumber;
            inValue.activityType = activityType;
            inValue.tribalLand = tribalLand;
            inValue.serviceType = serviceType;
            inValue.rateGroup = rateGroup;
            inValue.modifiedEffectiveDate = modifiedEffectiveDate;
            inValue.directApplication = directApplication;
            inValue.SSN4 = SSN4;
            inValue.dateOfBirth = dateOfBirth;
            LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse retVal = ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).DirectApplicationRequest(inValue);
            return retVal.DirectApplicationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse> LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.DirectApplicationRequestAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest request) {
            return base.Channel.DirectApplicationRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestResponse> DirectApplicationRequestAsync(
                    LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, 
                    string ocn, 
                    string subscriberAccountNumber, 
                    string customerCode, 
                    string ultsTelephoneNumber, 
                    string namePrefix, 
                    string firstName, 
                    string initials, 
                    string lastName, 
                    string nameSuffix, 
                    string serviceAddress1, 
                    string serviceAddress2, 
                    string serviceAddressCity, 
                    string serviceAddressState, 
                    string serviceAddressZip5, 
                    string serviceAddressZip4, 
                    string billingFirstName, 
                    string billingInitial, 
                    string billingLastName, 
                    string billingAddress1, 
                    string billingAddress2, 
                    string billingAddress3, 
                    string billingAddress4, 
                    string billingAddress5, 
                    string billingCity, 
                    string billingStateCode, 
                    string billingZip5, 
                    string billingZip4, 
                    string contactPhoneNumber, 
                    string languageCode, 
                    string brailleLargeFont, 
                    string ultsServiceStartDate, 
                    string ultsRecertificationDate, 
                    string priorUltsTelephoneNumber, 
                    string disconnectDate, 
                    string ttyQualifiedSecondLine, 
                    string driversLicenseNumber, 
                    string activityType, 
                    string tribalLand, 
                    string serviceType, 
                    string rateGroup, 
                    string modifiedEffectiveDate, 
                    string directApplication, 
                    string SSN4, 
                    string dateOfBirth) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.ocn = ocn;
            inValue.subscriberAccountNumber = subscriberAccountNumber;
            inValue.customerCode = customerCode;
            inValue.ultsTelephoneNumber = ultsTelephoneNumber;
            inValue.namePrefix = namePrefix;
            inValue.firstName = firstName;
            inValue.initials = initials;
            inValue.lastName = lastName;
            inValue.nameSuffix = nameSuffix;
            inValue.serviceAddress1 = serviceAddress1;
            inValue.serviceAddress2 = serviceAddress2;
            inValue.serviceAddressCity = serviceAddressCity;
            inValue.serviceAddressState = serviceAddressState;
            inValue.serviceAddressZip5 = serviceAddressZip5;
            inValue.serviceAddressZip4 = serviceAddressZip4;
            inValue.billingFirstName = billingFirstName;
            inValue.billingInitial = billingInitial;
            inValue.billingLastName = billingLastName;
            inValue.billingAddress1 = billingAddress1;
            inValue.billingAddress2 = billingAddress2;
            inValue.billingAddress3 = billingAddress3;
            inValue.billingAddress4 = billingAddress4;
            inValue.billingAddress5 = billingAddress5;
            inValue.billingCity = billingCity;
            inValue.billingStateCode = billingStateCode;
            inValue.billingZip5 = billingZip5;
            inValue.billingZip4 = billingZip4;
            inValue.contactPhoneNumber = contactPhoneNumber;
            inValue.languageCode = languageCode;
            inValue.brailleLargeFont = brailleLargeFont;
            inValue.ultsServiceStartDate = ultsServiceStartDate;
            inValue.ultsRecertificationDate = ultsRecertificationDate;
            inValue.priorUltsTelephoneNumber = priorUltsTelephoneNumber;
            inValue.disconnectDate = disconnectDate;
            inValue.ttyQualifiedSecondLine = ttyQualifiedSecondLine;
            inValue.driversLicenseNumber = driversLicenseNumber;
            inValue.activityType = activityType;
            inValue.tribalLand = tribalLand;
            inValue.serviceType = serviceType;
            inValue.rateGroup = rateGroup;
            inValue.modifiedEffectiveDate = modifiedEffectiveDate;
            inValue.directApplication = directApplication;
            inValue.SSN4 = SSN4;
            inValue.dateOfBirth = dateOfBirth;
            return ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).DirectApplicationRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.CheckApplicationPrintStatus(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest request) {
            return base.Channel.CheckApplicationPrintStatus(request);
        }
        
        public string CheckApplicationPrintStatus(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, string documentId, string transactionId) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.documentId = documentId;
            inValue.transactionId = transactionId;
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse retVal = ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).CheckApplicationPrintStatus(inValue);
            return retVal.CheckApplicationPrintStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse> LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap.CheckApplicationPrintStatusAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest request) {
            return base.Channel.CheckApplicationPrintStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusResponse> CheckApplicationPrintStatusAsync(LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationRequestSoapHeader DirectApplicationRequestSoapHeader, string documentId, string transactionId) {
            LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest inValue = new LS.Repositories.CaliforniaLifelineDireactApplicationService.CheckApplicationPrintStatusRequest();
            inValue.DirectApplicationRequestSoapHeader = DirectApplicationRequestSoapHeader;
            inValue.documentId = documentId;
            inValue.transactionId = transactionId;
            return ((LS.Repositories.CaliforniaLifelineDireactApplicationService.DirectApplicationWrapperServiceSoap)(this)).CheckApplicationPrintStatusAsync(inValue);
        }
    }
}
