-- Certain LifelinePrograms will require additional StateProgram verification
-- StatePrograms will have to be inserted first to populate those FKs.
-- Info for which LifelinePrograms have this requirement can be found in the TableData Excel file.

INSERT INTO [dbo].[LifelinePrograms] ([Id], [ProgramName], [StateCode], [RequiresAccountNumber], [RequiredStateProgramId], [RequiredSecondaryStateProgramId], [DateCreated], [DateModified], [IsDeleted], [NladEligibilityCode]) VALUES 
  (NEWID(), 'Annual Income', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'AL', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'AL', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'AL', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'AL', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'AL', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'AL', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'AR', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'AR', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'AR', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'AR', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'AR', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'AR', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'AZ', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'AZ', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Food Stamps', 'AZ', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'AZ', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'AZ', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'AZ', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'AZ', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Telephone Assistance Program for the Medically Needy', 'AZ', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Temporary Assistance for Needy Families', 'AZ', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Annual Income', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Medicaid/Medi-Cal', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, '')
, (NEWID(), 'Supplemental Nutrition Assistance Program (SNAP)/Cal-Fresh', 'CA', 1, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, '')
, (NEWID(), 'Temporary Assistance for Needy Families (TANF)/CAlworks/Stan Works/Welfare to Work/GAIN', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Head Start Program (income based only)', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, '')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'CA', 0, null, null, GETDATE(), GETDATE(), 0, 'E11')
, (NEWID(), 'Women, Infants and Children Program ', 'CA', 1, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Annual Income', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, '')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'CO', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'CO', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'CO', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'CO', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'CO', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'CO', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'GA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'GA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'GA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'GA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Senior Citizen Low-Income Discount Plan', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Temporary Assistance for Needy Families', 'GA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'GA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'HI', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'HI', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'HI', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'HI', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'HI', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'HI', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'IA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'IA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'IA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'IA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'IA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'IA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'ID', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'ID', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'ID', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'ID', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'ID', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'ID', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'IN', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'IN', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'IN', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'IN', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'IN', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'IN', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'General Public Assistance', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Medicaid', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'KS', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally Administered Free Lunch Program (income based only)', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'KS', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Annual Income', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'KY', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'KY', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'KY', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'KY', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'KY', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'KY', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'LA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'LA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'LA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'LA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'LA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'LA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Emergency Aid to the Elderly, Disabled and Children', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'MassHealth', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'Medicaid', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'National School Lunch (free program only)', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Transitional Aid to Families with Dependent Children', 'MA', 1, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Tribally Administered Free Lunch Program (income based only)', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'MA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Annual Income', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Electrical Universal Service Program', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Maryland Energy Assistance Program', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'Medicaid', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Medical Assistance', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'National School Lunch (free program only)', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Public Assistance to Adults', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Nutrition Assistance Program', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Security Income', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Temporary Assistance for Needy Families', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Temporary Cash Assistance', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Temporary Disability Assistance Program', 'MD', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'MD', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Annual Income', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Emergency Assistance Program', 'ME', 1, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Home Energy Assistance Program', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Maine Care', 'ME', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'Medicaid', 'ME', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'National School Lunch (free program only)', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Nutrition Assistance Program', 'ME', 1, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Temporary Assistance for Needy Families', 'ME', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'ME', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'MI', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'MI', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'MI', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'MI', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'MI', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'MI', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Food Stamps', 'MN', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'MN', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'Minnesota Family Investment Program', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'National School Lunch (free program only)', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Security Income', 'MN', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'MN', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Annual Income', 'MO', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'MO', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Food Stamps', 'MO', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'MO', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'MO HealthNet', 'MO', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'MO', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Security Income', 'MO', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'MO', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Annual Income', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'ND', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'ND', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'ND', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'ND', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'ND', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'ND', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'NE', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'NE', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'NE', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'NE', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Annual Income', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'NV', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'NV', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'NV', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'NV', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'NV', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'NV', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Food Stamps', 'OH', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'General/Disability Assistance', 'OH', 1, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Medicaid', 'OH', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'SSI-Blind and Disabled', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'OH', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Temporary Assistance for Needy Families', 'OH', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Aid to Families with Dependent Children', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Certified by the OK Tax Commission to participate in or receive assistance or benefits pursuant to the Sales Tax Relief Act, 68 O.S. § 5011 et seq', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Certified program by the State Dept. of Rehabilitation, providing vocational rehabilitation assistance or benefits, including hearing impaired', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Head Start Programs (under income qualifying eligibility provision only)', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Medicaid', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'OK', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'OK', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'PA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'PA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'PA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'PA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'PA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'PA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Medicaid', 'PR', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Puerto Rico Nutritional Assistance Program (PAN)', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'PR', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Temporary Assistance for Needy Families', 'PR', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Annual Income', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Family Independence Program', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'General Public Assistance', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Medicaid', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Rhode Island Medical Assistance Program', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Rhode Island Pharmaceutical Assistance to Elderly', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'RI Works', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Nutrition Assistance Program', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Security Income', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Temporary Assistance for Needy Families', 'RI', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'RI', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'SC', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'SC', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'SC', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'SC', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'SC', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'SC', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'SD', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'SD', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'SD', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'SD', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'SD', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'SD', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'TX', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'TX', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'TX', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'TX', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'TX', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'TX', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'UT', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'UT', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'UT', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'UT', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'UT', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Head Start Program (income based only)', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'UT', 0, null, null, GETDATE(), GETDATE(), 0, 'E11')
, (NEWID(), 'Annual Income', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'VT', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'VT', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'VT', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'VT', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'VT', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'VT', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Annual Income', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'WA', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'WA', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'WA', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'WA', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'WA', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Head Start Program (income based only)', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'WA', 0, null, null, GETDATE(), GETDATE(), 0, 'E11')
, (NEWID(), 'Annual Income', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'BadgerCare', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'Medical Assistance', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'National School Lunch (free program only)', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Supplemental Security Income', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'WI Homestead Tax Credit (Schedule H)', 'WI', 0, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Wisconsin Works (W2)', 'WI', 1, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Annual Income', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Emergency Assistance', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'School Clothing Allowance', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Supplemental Security Income', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Temporary Assistance for Needy Families', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'WV', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
, (NEWID(), 'WV Childrens Health Insurance Program (WV CHIP)', 'WV', 1, null, null, GETDATE(), GETDATE(), 0, 'E9')
, (NEWID(), 'Annual Income', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E12')
, (NEWID(), 'Bureau of Indian Affairs General Assistance', 'WY', 1, null, null, GETDATE(), GETDATE(), 0, 'E13')
, (NEWID(), 'Federal Housing Assistance (Section 8)', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E8')
, (NEWID(), 'Food Distribution Program on Indian Reservations', 'WY', 1, null, null, GETDATE(), GETDATE(), 0, 'E4')
, (NEWID(), 'Food Stamps', 'WY', 1, null, null, GETDATE(), GETDATE(), 0, 'E10')
, (NEWID(), 'Low Income Home Energy Assistance Program', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E2')
, (NEWID(), 'Medicaid', 'WY', 1, null, null, GETDATE(), GETDATE(), 0, 'E5')
, (NEWID(), 'National School Lunch (free program only)', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E1')
, (NEWID(), 'Supplemental Security Income', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E7')
, (NEWID(), 'Temporary Assistance for Needy Families', 'WY', 1, null, null, GETDATE(), GETDATE(), 0, 'E3')
, (NEWID(), 'Tribally-Administered Temporary Assistance for Needy Families', 'WY', 0, null, null, GETDATE(), GETDATE(), 0, 'E6')
