INSERT INTO [dbo].[TpivProofDocumentTypes] ([Id], [Type], [Name], [LifelineSystem], [LifelineSystemId], [DateCreated], [DateModified], [IsDeleted]) VALUES (NEWID(), 'SSN', 'Current Income Statement from and Employer, Paycheck Stub, or W-2', 'NLAD', 'T3', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Government Assistance Program Document which includes name and date of birth', 'NLAD', 'T14', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Military Discharge Documentation', 'NLAD', 'T12', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Prior Years State, Federal or Tribal Tax Return', 'NLAD', 'T4', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Social Security Card', 'NLAD', 'T5', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Statement of Benefits from a Qualifying Program which contains name and date of birth', 'NLAD', 'T15', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Unemployment/Workers Compensation Statement', 'NLAD', 'T16', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'US Government, Military, State, or Tribal Issued ID', 'NLAD', 'T8', GETDATE(), GETDATE(), 0)
, (NEWID(), 'SSN', 'Weapons Permit', 'NLAD', 'T13', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Birth Certificate', 'NLAD', 'T2', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Certificate of Naturalization or Certificate of U.S. Citizenship', 'NLAD', 'T6', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Drivers License', 'NLAD', 'T1', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Government Assistance Program Document which includes name and date of birth', 'NLAD', 'T14', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Military Discharge Documentation', 'NLAD', 'T12', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Passport', 'NLAD', 'T10', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Permanent Resident Card or Permanent Resident Alien Card', 'NLAD', 'T7', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Statement of Benefits from a Qualifying Program which contains name and date of birth', 'NLAD', 'T15', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Unemployment/Workers Compensation Statement', 'NLAD', 'T16', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'US Government, Military, State, or Tribal Issued ID', 'NLAD', 'T8', GETDATE(), GETDATE(), 0)
, (NEWID(), 'DOB', 'Weapons Permit', 'NLAD', 'T13', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Birth Certificate', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Certificate of Naturalization or Certificate of U.S. Citizenship', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Current Income Statement from and Employer, Paycheck Stub, or W-2', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Drivers License', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Government Assistance Program Document which includes name and date of birth', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Military Discharge Documentation', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Passport', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Permanent Resident Card or Permanent Resident Alien Card', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Prior Years State, Federal or Tribal Tax Return', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Social Security Card', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Statement of Benefits from a Qualifying Program which contains name and date of birth', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Unemployment/Workers Compensation Statement', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'US Government, Military, State, or Tribal Issued ID', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Weapons Permit', 'DAP', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Birth Certificate', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Certificate of Naturalization or Certificate of U.S. Citizenship', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Current Income Statement from and Employer, Paycheck Stub, or W-2', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Drivers License', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Government Assistance Program Document which includes name and date of birth', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Military Discharge Documentation', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Passport', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Permanent Resident Card or Permanent Resident Alien Card', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Prior Years State, Federal or Tribal Tax Return', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Social Security Card', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Statement of Benefits from a Qualifying Program which contains name and date of birth', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Unemployment/Workers Compensation Statement', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'US Government, Military, State, or Tribal Issued ID', 'TEXAS', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'All', 'Weapons Permit', 'TEXAS', '', GETDATE(), GETDATE(), 0)
