-- ProofType of 'id' apply to every state which is why their value for StateCode is null (Except in the case of California). 
-- Queries intending to include the program ProofDocumentTypes for a State as well as the id ProofDocumentTypes (except CA) should query "WHERE StateCode = 'EX' OR StateCode = null".

INSERT INTO [dbo].[ProofDocumentTypes] ([Id], [ProofType], [Name], [StateCode], [DateCreated], [DateModified], [IsDeleted]) VALUES (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'AR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Arizona Low-Income Telephone Assistance Program /Telephone Assistance Program for the Medically Needy (ALITAP) award letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'State Children’s Health Insurance Plan (SCHIP) or KidsCare (Medicaid)', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'AZ', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', '1099 Distribution', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bank Statement with SSI direct deposit', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Certificate of Eligbility for Exchange Vistor status (only if Section 5 is completed)', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'General/Disability Assistance award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 consecutive paycheck stubs', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid/Medi-Cal card/awards letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Passport to Services (CAL-Fresh and CAL-Works Programs only)', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SNAP/Cal-Fresh card/letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF)/CalWorks/Stan Works/Welfare to Work/GAIN award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribal Head Start Programs (under income qualifying eligibility provision only) award letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Women, Infants and Children Program card/awards letter/voucher', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Worker''s Compensation Appeals Board Award Letter', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'CO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Utility Bill with Senior Discount / Senior Citizen Low-income Discount plan letter', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'GA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 consecutive months paycheck stubs', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'HI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'IA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'ID', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'IN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'General Public Assistance (GPA) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Kansas Lifeline Service Program (KLSP) Database', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally Administered Heard Start Program award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'KS', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'KY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'LA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', ' Disabled and Children (EAEDC) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Emergency Aid to the Elderly', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'MassHealth card/award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Transitional Aid to Families with Dependent Children (TAFDC) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally Administered Heard Start Program award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'MA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Electrical Universal Service Program (EUSP) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Maryland Energy Assistance Program (MEAP) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medical Assistance (MA) card/award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Public Assistance to Adults (PAA) awards letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tel-Life Database', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Cash Assistance (TCA) awards letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Disability Assistance Program (TDAP) awards letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'MD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Emergency Assistance Program award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Home Energy Assistance Program (HEAP) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Maine Care award letter/card', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'ME', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 consecutive paycheck stubs', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Michigan Lifeline Eligibility Database', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'MI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Minnesota Family Investment Program (MFIP) award letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'MN', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'MO Health', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'MO', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'ND', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'E-MAC award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Kids Connection card/award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'MAC card/award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SAM card/award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'NE', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Department of Health and Human Services DSHS Database', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'NV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'General/Disability Assistance award letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI - Blind and Disabled (SSDI) award letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'OH', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Aid to Families with Dependent Children award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Certified by the OK Tax Commission to participate in or receive assistance or benefits pursuant to the Sales Tax Relief Act, 68 O.S. Â§ 5011 et seq.', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Certified program by the State Dept. of Rehabilitation, providing vocational rehabilitation assistance or benefits, including hearing impaired)', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Head Start Programs (under income qualifying eligibility provision only) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'OK', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Pennsylvania DPW Lifeline Database', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'PA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Puerto Rico Nutritional Assistance Program(PAN) award letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'PR', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Family Independence Program (FIP) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'General Public Assistance (GPA) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Rhode Island Medical Assistance Program (MAP) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Rhode Island Pharmaceutical Assistance to Elderly (RIPAE) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Rhode Island Works (Formerly known as AFDC) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'RI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'SC', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'SD', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Lite-UP Texas Eligibility System Database (Solix)', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program Benfits Letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Texas Affidavit for Indigent Consumer', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Texas Annual Income Affidavit For Individuals Exiting a Texas Correctional Facility', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'TX', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Head Start (Income based qualification only) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'UT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Vermont Department for Children and Families Database', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'VT', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally Administered Heard Start Program award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'WA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'BadgerCare card/award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medical Assistance (MA) card/award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'WI Homestead Tax Credit (Schedule H) award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Wisconsin Cares Database', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Wisconsin Works (W2) statement/award letter', 'WI', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Emergency Assistance Program award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'School Clothing Allowance (SCA) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'WV Children''s Health Insurance Program (WV CHIP) card/award letter', 'WV', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Bureau of Indian Affairs General Assistance (BIA) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Divorce decree or child support document', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Federal Housing Assistance/Section 8 Housing Awards Letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food Distribution Program on Indian Reservations (FDPIR) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Food stamp/SNAP card/letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Last 3 months of consecutive paycheck stubs', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Low Income Home Energy Assistance Program (LIHEAP) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Medicaid card/letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'National Administered Free Lunch Program', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Prior year''s state, federal or tribal tax return (W2)', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Retirement/pension benefit statement', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Social Security benefits statement', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'SSI (Supplement Security Income) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Temporary Assistance to Needy Families (TANF) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Tribally-Administered Temporary Assistance for Needy Families (TTANF) award letter', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Unemployment/Workers Compensation benefits statement', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'program', 'Veterans Administration benefits statement', 'WY', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Unexpired United States Driver''s License', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Unexpired UNITED STATES Government, Military, State, or Tribal Issued ID', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Unexpired Permanent Resident Card and/or Unexpired Permanent Resident Alien Card', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Unexpired United States Passport', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Prison Issued Identification Cards', '', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'U.S. Driver License', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Certificate of U.S. Citizenship', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Certificate of Naturalization or Citizenship', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'U.S. Passport/U.S. Territory Passport', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Foreign Passport', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'U.S. government, military, state of Tribal issued-ID, which includes DOB and/or SSN and/or Tribal ID', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'U.S. Military ID cards (active or reserve duty, dependent of a military member, retired member, discharged from service, medical/religious personnel)', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Common Access Card (only if designated as Active Military or Active Reserve or Active Selected Reserve)', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Military Discharge documentation, which includes DOB and/or SSN and/or Tribal ID', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Northern Mariana Card', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Permanent Resident Card', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Permanent Resident Alien Card', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Permanent Resident Re-Entry Permit', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Temporary Resident Identification Card', 'CA', GETDATE(), GETDATE(), 0)
, (NEWID(), 'id', 'Employment Authorization Card', 'CA', GETDATE(), GETDATE(), 0)
