// <auto-generated />
namespace LS.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20161207jwsyncfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161207jwsyncfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071946371_20161207-jwsyncfix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
