// <auto-generated />
namespace LS.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class House_Numbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(House_Numbers));
        
        string IMigrationMetadata.Id
        {
            get { return "201606102213075_House_Numbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
