// <auto-generated />
namespace LS.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ExternalDataTrueUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExternalDataTrueUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201608022042505_ExternalDataTrueUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
