// <auto-generated />
namespace LS.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class HandsetTableUpates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HandsetTableUpates));
        
        string IMigrationMetadata.Id
        {
            get { return "201703162139406_HandsetTableUpates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
