//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Services.ServiceObjectsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com/", ConfigurationName="ServiceObjectsService.DOTSAddressValidateSoap")]
    public interface DOTSAddressValidateSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.Address ValidateAddress(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.Address> ValidateAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithFragments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.FragmentAddress ValidateAddressWithFragments(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithFragments", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ValidateAddressWithFragmentsAsync(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ParseAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.FragmentAddress ParseAddress(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ParseAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ParseAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithExtras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.Address ValidateAddressWithExtras(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithExtras", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.Address> ValidateAddressWithExtrasAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/GetPossibleMatches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.FragmentAddress[] GetPossibleMatches(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/GetPossibleMatches", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress[]> GetPossibleMatchesAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.AddressType ValidateAddressType(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressType", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.AddressType> ValidateAddressTypeAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressSingleLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.FragmentAddress ValidateAddressSingleLine(string Address, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressSingleLine", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ValidateAddressSingleLineAsync(string Address, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateCityStateZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.AreaAddress ValidateCityStateZip(string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateCityStateZip", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.AreaAddress> ValidateCityStateZipAsync(string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithDPV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.DPVAddress ValidateAddressWithDPV(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithDPV", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.DPVAddress> ValidateAddressWithDPVAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithSuiteLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.DPVAddress ValidateAddressWithSuiteLink(string BusinessName, string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithSuiteLink", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.DPVAddress> ValidateAddressWithSuiteLinkAsync(string BusinessName, string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithRDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LS.Services.ServiceObjectsService.RDIAddress ValidateAddressWithRDI(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ValidateAddressWithRDI", ReplyAction="*")]
        System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.RDIAddress> ValidateAddressWithRDIAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string address2Field;
        
        private string barcodeDigitsField;
        
        private string carrierRouteField;
        
        private string congressCodeField;
        
        private string countyCodeField;
        
        private string countyNameField;
        
        private string fragmentField;
        
        private string exceptionField;
        
        private Err errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address", Order=0)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BarcodeDigits {
            get {
                return this.barcodeDigitsField;
            }
            set {
                this.barcodeDigitsField = value;
                this.RaisePropertyChanged("BarcodeDigits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CongressCode {
            get {
                return this.congressCodeField;
            }
            set {
                this.congressCodeField = value;
                this.RaisePropertyChanged("CongressCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
                this.RaisePropertyChanged("Fragment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class Err : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private string numberField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class RDIAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string address2Field;
        
        private string isResidentialField;
        
        private string barcodeDigitsField;
        
        private string carrierRouteField;
        
        private string congressCodeField;
        
        private string countyCodeField;
        
        private string countyNameField;
        
        private string fragmentField;
        
        private string fragmentHouseField;
        
        private string fragmentPMBNumberField;
        
        private string fragmentPMBPrefixField;
        
        private string fragmentPostDirField;
        
        private string fragmentPreDirField;
        
        private string fragmentStreetField;
        
        private string fragmentSuffixField;
        
        private string fragmentUnitField;
        
        private string sourceField;
        
        private string dPVField;
        
        private string dPVDescField;
        
        private string dPVNotesField;
        
        private string dPVNotesDescField;
        
        private string correctionsField;
        
        private string correctionsDescField;
        
        private Err errorField;
        
        private string debugField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IsResidential {
            get {
                return this.isResidentialField;
            }
            set {
                this.isResidentialField = value;
                this.RaisePropertyChanged("IsResidential");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BarcodeDigits {
            get {
                return this.barcodeDigitsField;
            }
            set {
                this.barcodeDigitsField = value;
                this.RaisePropertyChanged("BarcodeDigits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CongressCode {
            get {
                return this.congressCodeField;
            }
            set {
                this.congressCodeField = value;
                this.RaisePropertyChanged("CongressCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
                this.RaisePropertyChanged("Fragment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FragmentHouse {
            get {
                return this.fragmentHouseField;
            }
            set {
                this.fragmentHouseField = value;
                this.RaisePropertyChanged("FragmentHouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FragmentPMBNumber {
            get {
                return this.fragmentPMBNumberField;
            }
            set {
                this.fragmentPMBNumberField = value;
                this.RaisePropertyChanged("FragmentPMBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FragmentPMBPrefix {
            get {
                return this.fragmentPMBPrefixField;
            }
            set {
                this.fragmentPMBPrefixField = value;
                this.RaisePropertyChanged("FragmentPMBPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FragmentPostDir {
            get {
                return this.fragmentPostDirField;
            }
            set {
                this.fragmentPostDirField = value;
                this.RaisePropertyChanged("FragmentPostDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FragmentPreDir {
            get {
                return this.fragmentPreDirField;
            }
            set {
                this.fragmentPreDirField = value;
                this.RaisePropertyChanged("FragmentPreDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string FragmentStreet {
            get {
                return this.fragmentStreetField;
            }
            set {
                this.fragmentStreetField = value;
                this.RaisePropertyChanged("FragmentStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FragmentSuffix {
            get {
                return this.fragmentSuffixField;
            }
            set {
                this.fragmentSuffixField = value;
                this.RaisePropertyChanged("FragmentSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string FragmentUnit {
            get {
                return this.fragmentUnitField;
            }
            set {
                this.fragmentUnitField = value;
                this.RaisePropertyChanged("FragmentUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DPV {
            get {
                return this.dPVField;
            }
            set {
                this.dPVField = value;
                this.RaisePropertyChanged("DPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string DPVDesc {
            get {
                return this.dPVDescField;
            }
            set {
                this.dPVDescField = value;
                this.RaisePropertyChanged("DPVDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DPVNotes {
            get {
                return this.dPVNotesField;
            }
            set {
                this.dPVNotesField = value;
                this.RaisePropertyChanged("DPVNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DPVNotesDesc {
            get {
                return this.dPVNotesDescField;
            }
            set {
                this.dPVNotesDescField = value;
                this.RaisePropertyChanged("DPVNotesDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
                this.RaisePropertyChanged("Corrections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CorrectionsDesc {
            get {
                return this.correctionsDescField;
            }
            set {
                this.correctionsDescField = value;
                this.RaisePropertyChanged("CorrectionsDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Debug {
            get {
                return this.debugField;
            }
            set {
                this.debugField = value;
                this.RaisePropertyChanged("Debug");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class DPVAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string address2Field;
        
        private string barcodeDigitsField;
        
        private string carrierRouteField;
        
        private string congressCodeField;
        
        private string countyCodeField;
        
        private string countyNameField;
        
        private string fragmentField;
        
        private string fragmentHouseField;
        
        private string fragmentPMBNumberField;
        
        private string fragmentPMBPrefixField;
        
        private string fragmentPostDirField;
        
        private string fragmentPreDirField;
        
        private string fragmentStreetField;
        
        private string fragmentSuffixField;
        
        private string fragmentUnitField;
        
        private string sourceField;
        
        private string dPVField;
        
        private string dPVDescField;
        
        private string dPVNotesField;
        
        private string dPVNotesDescField;
        
        private string correctionsField;
        
        private string correctionsDescField;
        
        private Err errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BarcodeDigits {
            get {
                return this.barcodeDigitsField;
            }
            set {
                this.barcodeDigitsField = value;
                this.RaisePropertyChanged("BarcodeDigits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CongressCode {
            get {
                return this.congressCodeField;
            }
            set {
                this.congressCodeField = value;
                this.RaisePropertyChanged("CongressCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
                this.RaisePropertyChanged("Fragment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FragmentHouse {
            get {
                return this.fragmentHouseField;
            }
            set {
                this.fragmentHouseField = value;
                this.RaisePropertyChanged("FragmentHouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FragmentPMBNumber {
            get {
                return this.fragmentPMBNumberField;
            }
            set {
                this.fragmentPMBNumberField = value;
                this.RaisePropertyChanged("FragmentPMBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FragmentPMBPrefix {
            get {
                return this.fragmentPMBPrefixField;
            }
            set {
                this.fragmentPMBPrefixField = value;
                this.RaisePropertyChanged("FragmentPMBPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FragmentPostDir {
            get {
                return this.fragmentPostDirField;
            }
            set {
                this.fragmentPostDirField = value;
                this.RaisePropertyChanged("FragmentPostDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FragmentPreDir {
            get {
                return this.fragmentPreDirField;
            }
            set {
                this.fragmentPreDirField = value;
                this.RaisePropertyChanged("FragmentPreDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FragmentStreet {
            get {
                return this.fragmentStreetField;
            }
            set {
                this.fragmentStreetField = value;
                this.RaisePropertyChanged("FragmentStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string FragmentSuffix {
            get {
                return this.fragmentSuffixField;
            }
            set {
                this.fragmentSuffixField = value;
                this.RaisePropertyChanged("FragmentSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FragmentUnit {
            get {
                return this.fragmentUnitField;
            }
            set {
                this.fragmentUnitField = value;
                this.RaisePropertyChanged("FragmentUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DPV {
            get {
                return this.dPVField;
            }
            set {
                this.dPVField = value;
                this.RaisePropertyChanged("DPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DPVDesc {
            get {
                return this.dPVDescField;
            }
            set {
                this.dPVDescField = value;
                this.RaisePropertyChanged("DPVDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string DPVNotes {
            get {
                return this.dPVNotesField;
            }
            set {
                this.dPVNotesField = value;
                this.RaisePropertyChanged("DPVNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DPVNotesDesc {
            get {
                return this.dPVNotesDescField;
            }
            set {
                this.dPVNotesDescField = value;
                this.RaisePropertyChanged("DPVNotesDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
                this.RaisePropertyChanged("Corrections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CorrectionsDesc {
            get {
                return this.correctionsDescField;
            }
            set {
                this.correctionsDescField = value;
                this.RaisePropertyChanged("CorrectionsDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class AreaAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string postalCodeFoundField;
        
        private Err errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostalCodeFound {
            get {
                return this.postalCodeFoundField;
            }
            set {
                this.postalCodeFoundField = value;
                this.RaisePropertyChanged("PostalCodeFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressType1Field;
        
        private string addressTypeDescriptionField;
        
        private Err errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressType", Order=0)]
        public string AddressType1 {
            get {
                return this.addressType1Field;
            }
            set {
                this.addressType1Field = value;
                this.RaisePropertyChanged("AddressType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressTypeDescription {
            get {
                return this.addressTypeDescriptionField;
            }
            set {
                this.addressTypeDescriptionField = value;
                this.RaisePropertyChanged("AddressTypeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public partial class FragmentAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string address2Field;
        
        private string barcodeDigitsField;
        
        private string carrierRouteField;
        
        private string congressCodeField;
        
        private string countyCodeField;
        
        private string countyNameField;
        
        private string fragmentField;
        
        private string fragmentHouseField;
        
        private string fragmentPMBNumberField;
        
        private string fragmentPMBPrefixField;
        
        private string fragmentPostDirField;
        
        private string fragmentPreDirField;
        
        private string fragmentStreetField;
        
        private string fragmentSuffixField;
        
        private string fragmentUnitField;
        
        private string sourceField;
        
        private Err errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BarcodeDigits {
            get {
                return this.barcodeDigitsField;
            }
            set {
                this.barcodeDigitsField = value;
                this.RaisePropertyChanged("BarcodeDigits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CongressCode {
            get {
                return this.congressCodeField;
            }
            set {
                this.congressCodeField = value;
                this.RaisePropertyChanged("CongressCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CountyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("CountyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
                this.RaisePropertyChanged("Fragment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FragmentHouse {
            get {
                return this.fragmentHouseField;
            }
            set {
                this.fragmentHouseField = value;
                this.RaisePropertyChanged("FragmentHouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FragmentPMBNumber {
            get {
                return this.fragmentPMBNumberField;
            }
            set {
                this.fragmentPMBNumberField = value;
                this.RaisePropertyChanged("FragmentPMBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FragmentPMBPrefix {
            get {
                return this.fragmentPMBPrefixField;
            }
            set {
                this.fragmentPMBPrefixField = value;
                this.RaisePropertyChanged("FragmentPMBPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FragmentPostDir {
            get {
                return this.fragmentPostDirField;
            }
            set {
                this.fragmentPostDirField = value;
                this.RaisePropertyChanged("FragmentPostDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FragmentPreDir {
            get {
                return this.fragmentPreDirField;
            }
            set {
                this.fragmentPreDirField = value;
                this.RaisePropertyChanged("FragmentPreDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FragmentStreet {
            get {
                return this.fragmentStreetField;
            }
            set {
                this.fragmentStreetField = value;
                this.RaisePropertyChanged("FragmentStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string FragmentSuffix {
            get {
                return this.fragmentSuffixField;
            }
            set {
                this.fragmentSuffixField = value;
                this.RaisePropertyChanged("FragmentSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FragmentUnit {
            get {
                return this.fragmentUnitField;
            }
            set {
                this.fragmentUnitField = value;
                this.RaisePropertyChanged("FragmentUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public Err Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOTSAddressValidateSoapChannel : LS.Services.ServiceObjectsService.DOTSAddressValidateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOTSAddressValidateSoapClient : System.ServiceModel.ClientBase<LS.Services.ServiceObjectsService.DOTSAddressValidateSoap>, LS.Services.ServiceObjectsService.DOTSAddressValidateSoap {
        
        public DOTSAddressValidateSoapClient() {
        }
        
        public DOTSAddressValidateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOTSAddressValidateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOTSAddressValidateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOTSAddressValidateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LS.Services.ServiceObjectsService.Address ValidateAddress(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddress(Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.Address> ValidateAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressAsync(Address, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.FragmentAddress ValidateAddressWithFragments(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithFragments(Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ValidateAddressWithFragmentsAsync(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithFragmentsAsync(Address, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.FragmentAddress ParseAddress(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ParseAddress(Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ParseAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ParseAddressAsync(Address, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.Address ValidateAddressWithExtras(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithExtras(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.Address> ValidateAddressWithExtrasAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithExtrasAsync(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.FragmentAddress[] GetPossibleMatches(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.GetPossibleMatches(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress[]> GetPossibleMatchesAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.GetPossibleMatchesAsync(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.AddressType ValidateAddressType(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressType(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.AddressType> ValidateAddressTypeAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressTypeAsync(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.FragmentAddress ValidateAddressSingleLine(string Address, string LicenseKey) {
            return base.Channel.ValidateAddressSingleLine(Address, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.FragmentAddress> ValidateAddressSingleLineAsync(string Address, string LicenseKey) {
            return base.Channel.ValidateAddressSingleLineAsync(Address, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.AreaAddress ValidateCityStateZip(string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateCityStateZip(City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.AreaAddress> ValidateCityStateZipAsync(string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateCityStateZipAsync(City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.DPVAddress ValidateAddressWithDPV(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithDPV(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.DPVAddress> ValidateAddressWithDPVAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithDPVAsync(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.DPVAddress ValidateAddressWithSuiteLink(string BusinessName, string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithSuiteLink(BusinessName, Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.DPVAddress> ValidateAddressWithSuiteLinkAsync(string BusinessName, string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithSuiteLinkAsync(BusinessName, Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public LS.Services.ServiceObjectsService.RDIAddress ValidateAddressWithRDI(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithRDI(Address, Address2, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<LS.Services.ServiceObjectsService.RDIAddress> ValidateAddressWithRDIAsync(string Address, string Address2, string City, string State, string PostalCode, string LicenseKey) {
            return base.Channel.ValidateAddressWithRDIAsync(Address, Address2, City, State, PostalCode, LicenseKey);
        }
    }
}
